<#
.SYNOPSIS
Checks NetApp VMware volume SMVI snapshots and makes sure the oldest backup isn't more than 8 days old and the newest backup isn't older than 2 days old.

.DESCRIPTION
This script connects to each CDOT cluster and 7-Mode node and gathers configuration information. This information can
    be used to rebuild in the event of a DR scenario.

.EXAMPLE
.\netappConfigBackup.ps1

.PARAMETER $logFileBasePath
This parameter defines the base path for the log output file of the script. (Where logs will be written)

.PARAMETER $logFileBaseName
The parameter defines the root of the scripts log output file name.

.PARAMETER $sendTo
This parameter defines the email destination for the standard script email output.

.PARAMETER $from
This parameter defines the from address for emails generated by the script.

.PARAMETER $smtpServer
This parameter defines the SMTP server to be used when the script sends an email.

.PARAMETER $cdotClusterListFile
This parameter defines the text file that contains all of the CDOT clusters to pull data from.

.PARAMETER $logFileRetentionDays
This parameter defines how long this script's log files are retained.

.PARAMETER $dataFileRetentionDays
This parameter defines how long the output data files from this script are kept.

.PARAMETER $backupAgeThreshold
This parameter defines the age upon which the script will alert for orphaned backup snapshots.

.PARAMETER $newestBackupDaysThreshold
This parameter defines the age upon which the script will alert that the most recent backup is too old and the previous backup job must have failed or have not run.

.NOTES
Author: duane.reed@powereng.com
Last revised: 25-Jan-17

Any other notes about the script (revision history, etc.)
Initial version 0.1 (25-Jan-17)
30-May-24 - Ken Briney
    Significantly modified the script.
    Changed the way volumes were excluded.
    Add SL_ volumes to the list of volumes to exclude.
    Merged both potential reports into a single report and added a "Status" column to indicate an orphaned snapshot or missed snapshot.

.LINK
An external link if needed. The syntax of comment-based help is available here:
http://technet.microsoft.com/en-us/library/hh847834.aspx

#>

#Configure script command line parameters
[cmdletbinding()]
Param
(
    [String]$logFileBasePath = "E:\Scripts\Logs\SMVI Backup Check\",
    [String]$logFileBaseName = "SnapCenterCheck",
    [String]$sendTo = "itstorage@powereng.com",
    [String]$from = "cdc-ntapmgmt01@powereng.com",
    [string]$smtpServer = "smtp.powereng.com",
    [String]$cdotClusterListFile = "E:\Scripts\Config\cdotList.txt",
    [int]$logFileRetentionDays = 30,
    [int]$dataFileRetentionDays = 7,
    [int]$backupAgeThreshold = 8,
    [int]$newestBackupDaysThreshold = 1
)

# Logging function
Function Out-LogFile
{
    <#
    .SYNOPSIS
    Writes data to a log file

    .DESCRIPTION
    Writes data to a log file. The format of the log file attempts to mimic the logging
    used by Configuration Manager, so that the log files will render nicely using cmtrace.

    .PARAMETER logText
    This is the string that will be written to the log file

    .PARAMETER overwrite
    By default, log file entries are appended to the specified log file. If this switch is specified,
    the log file will be overwritten.

    .PARAMETER type
    Determines the type of message that will be written to a log. The default value is 1:
    1 - Information
    2 - Warning
    3 - Error

    .PARAMETER logFile
    The name of the log file where messages will be written.
    #>

    Param
    (
        [String]$logText,
        [Switch]$overwrite,
        [string]$type = 1,
        [String]$logFile = $logFile
    )

    # Do nothing if no log file is defined
    if (!$logFile)
    {
        return
    } `
    else
    {
        #Create the time stamp for the log entry
        $time = Get-Date -Format HH:mm:ss.fff
        $offset = ([int](Get-Date -Format %z) * -60).ToString().PadLeft(3, "0").PadLeft(4, "+")
        $day = Get-Date -Format MM-dd-yyyy
        $component = $MyInvocation.ScriptName | Split-Path -Leaf
        $string = "<![LOG[$logText]LOG]!>" +
        "<time=`"$time$offset`" " +
        "date=`"$day`" " +
        "component=`"$component`" " +
        "context=`"$env:USERNAME`" " +
        "type=`"$type`" " +
        "thread=`"$PID`" " +
        "file=`"$component`">"
        #Write the data to the log file
        Write-Verbose $logText
        $string | Out-File  -FilePath $logFile -Force -Encoding utf8 -Append:$(!$overwrite)
    }#End else
}#End Out-Log Function

$currentDate = Get-Date
$logFile = "{0}{1} - {2}.log" -f @($logFileBasePath, $logFileBaseName,$currentDate.ToString("yyyyMMdd-HHmmss"))

if (!(Test-Path -Path $logFileBasePath))
{
    New-Item -Path $logFileBasePath -ItemType "Directory" | Out-Null
}

#=========================END SKELETON=========================#

#=================================================================================================================
#
# For CDOT connections, since they use https, you have to catpure logins via the NetApp Powershell toolkit
#  so that they can be accessed magically when you run a scheduled task non-interactively.
#
# To capture credentials (encrypted of course) to be available at scheduled task run time, perform the following.
#
#  First: Capture login and password as follows:
#   $credentials = Get-Credential -Credential POWERENG\<ACCOUNT NAME>
#
#  Second: Add the capture credentials to the NetApp PowerShell toolkit cache.
#   Add-NcCredential -Name "<CLUSTER FQDN>" -Credential $credentials
#   Repeat this r
#
#  Third: Verify credentials
#   Get-NcCredential
#
#==================================================================================================================

Function Connect-Cluster
{
    Param
    (
        $clusters
    )

    foreach ($cluster in $clusters)
    {
        Out-LogFile "Connecting to CDOT cluster $cluster."
        $connection = Connect-NcController -Name $cluster

        if ($connection)
        {
            [void]$cdotConnectionArrayList.Add($connection)
        } `
        else
        {
            Out-LogFile "FAILURE: Could not connect to $cluster."
            Write-Host "FAILURE: Could not connect to $cluster."
            $Script:failMessages += "FAILURE: Could not connect to $cluster.`n"
        }

        $connection = $null
    }
}

if (!(Get-Module -Name DataONTAP))
{
    Import-Module DataONTAP
}


if (Test-Path -Path $cdotClusterListFile)
{
    #Confgure HTML settings
    $html = "<style>"
    $html = $html + "BODY{background-color:White;}"
    $html = $html + "TABLE{border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}"
    $html = $html + "TH{border-width: 1px;padding: 5px;border-style: solid;border-color: black;background-color: green}"
    $html = $html + "TD{border-width: 1px;padding: 5px;text-align: center;border-style: solid;border-color: black;background-color: Silver}"
    $html = $html + "</style>"

    $cdotConnectionArrayList = New-Object System.Collections.ArrayList
    $snapshotsToReport = [System.Collections.Generic.List[System.Object]]::new()
    $cdotClusterList = Get-Content -Path $cdotClusterListFile

    # We don't care about volumes which match the follow...
    $volumesToIgnoreRegex = "^(JP_)|(ROOT_)|(vol0)|(SMD_)|(SL_)"

    foreach ($cluster in $cdotClusterList)
    {
        Connect-Cluster $cluster
    }

    # Get all snapshots named "SnapCenterBkp*" from all volumes and exclude the ones we want to ignore.
    $snapShots = Get-NcSnapshot -Controller $cdotConnectionArrayList -SnapName "SnapCenterBkp*" -Volume "*vmware*" | Where-Object { ($_.Volume -notmatch $volumesToIgnoreRegex) }

    # Now incrementally group snapshots by controller...
    $snapShotsByController = $snapShots | Group-Object -Property NcController
    $a = 0
    while($a -lt $snapShotsByController.Length)
    {
        # ... then group by vserver
        $snapshotsByControllerAndVServer = $snapShotsByController[$a].Group | Group-Object VServer
        $b = 0
        while($b -lt $snapshotsByControllerAndVServer.Length)
        {
            # ... and finally, group by volume.
            $snapshotsByControllerVServerAndVolume = $snapshotsByControllerAndVServer[$b].Group | Group-Object -Property Volume

            # Now, for each volume, find stale and orphaned snapshots and add them to the list of snapshot to include in the report.
            $c = 0
            while($c -lt $snapshotsByControllerVServerAndVolume.Length)
            {
                # Get the newest snapshot for the volume and determine if it is more than $newestBackupDaysThreshold days old -- This will be the most recent, but stale snapshot, signalling a missed backup.
                $staleSnapshots = @($snapshotsByControllerVServerAndVolume[$c].Group | Sort-Object -Descending -Property Created | Select-Object -First 1 | Where-Object { ($currentDate - $_.Created).TotalDays -gt $newestBackupDaysThreshold } )
                $staleSnapshots.ForEach({
                    $snapshotsToReport.Add($_)
                    Out-LogFile ("Most recent backup is too old. Assuming failure on volume {0}:{1}:{2}. Snapshot: {3}, created {4}." -f @($_.NcController.Name, $_.VServer, $_.Volume, $_.Name, $_.Created))
                })

                # Get all snapshots for the volume which are more than $backupAgeThreshold days old -- These are snapshots which SnapCenter failed to clean up.
                $orphanedSnapshots = @($snapshotsByControllerVServerAndVolume[$c].Group | Where-Object { ($currentDate - $_.Created).TotalDays -gt $backupAgeThreshold })
                $orphanedSnapshots.ForEach({
                    $snapshotsToReport.Add($_)
                    Out-LogFile ("Orphaned snapshot found on volume {0}:{1}:{2}. Snapshot: {3}, created {4}, age: {5} days." -f @($_.NcController.Name, $_.VServer, $_.Volume, $_.Name, $_.Created, ($currentDate - $_.Created).TotalDays))
                })

                $c++
            }
            $b++
        }
        $a++
    }

    # If there are any missing or orphaned snapshots, then send a report.
    if($snapshotsToReport.Count -gt 0)
    {
        Out-LogFile ("Sending VM backup report to {0} using server {1}." -f @($sendTo, $smtpServer))

        # create the report email message object
        $reportMessage = New-Object System.Net.Mail.MailMessage $from, $sendTo

        #Create the SMTP client object.
        $smtp = New-Object Net.Mail.SmtpClient($smtpServer)

        $reportMessage.Subject = "VM Backup report for {0}" -f @($currentDate.ToString("M/d/yyyy"))
        $reportMessage.Body = $snapshotsToReport | Select-Object @{N='Status';E={ if(($currentDate - $_.Created).TotalDays -gt $backupAgeThreshold) { "Orphaned" } else { "Missed" }}},Vserver, Volume, @{N='Age-Days';E={($currentDate - $_.Created).TotalDays.ToString("N2")}},@{N='Snapshot-Name';E={$_.Name}}, Created | Sort-Object Status, Vserver, Volume, Age-Days | ConvertTo-Html -Head $html
        $reportMessage.IsBodyHTML = $true

        #Send it!
        $smtp.Send($reportMessage)
        $smtp.Dispose()
    } `
    else
    {
        # Nothing, no report to send.
    }
} `
else
{
    Out-Logfile "FAILURE: Could not find the cdot file, $cdotClusterListFile."
    Write-Host "FAILURE: Could not find the cdot file, $cdotClusterListFile."
    $failMessages += "FAILURE: Could not find the cdot file, $cdotClusterListFile.`n"
}
