[CmdLetBinding()]
Param(
    # CSV File generated by ExportNCCIFSSharesToCSV.
    [Parameter(Mandatory=$true,Position=0)]
    [String]
    $translationCSVPath,

    # Top level folder where individual scan data is saved to.
    [Parameter(Mandatory=$true,Position=1)]
    [String]
    $dataSaveFolder,

    # Path to an external script used to scan each Shares$ share listed in $translationCSVPath
    [Parameter(Mandatory=$true,Position=2)]
    [String]
    $scannerScriptPath,     # "C:\Users\kbriney-adm\PSScripts\Repos\PEI-IT-OPS\Dataclassification\shell.ps1"

    # Maximum number of $scannerScriptPath script to allow at a time
    [Parameter(Mandatory=$false,Position=3)]
    [Int32]
    $maxRunSlots =  15,

    # Maximum number of $scannerScriptPath script to allow at a time
    [Parameter(Mandatory=$false,Position=4)]
    [String[]]
    $clustersToInclude = @(),  # CDOT cluster(s) to scan...

    [Parameter(Mandatory=$false,Position=5)]
    [Switch]
    $NonRootShares
)


<#
    POWER Engineers CIFS shares are hosted on NetApp ONTAP clusters.  They all use the following pattern.

    CIFS_Server
        Shares$      Hidden share at the top of all shares hosted from a CIFS Server
            Share01
            Share02
            Share03

    In the above example user data would be accessed using \\CIFS_Server\Share01, \\CIFS_Server\Share03, or \\CIFS_Server\Share03.  However, \\CIFS_Server\Shares$ would also
    allow access to Share01, Share02, and Share03 as follows: \\CIFS_Server\Shares$\Share01, \\CIFS_Server\Shares$\Share02, and \\CIFS_Server\Shares$\Share03.  Knowing this,
    it is possible to scan all shares using a single share...Shares$.

    Most of the heavy lifting is in another script: $scannerScriptPath.  I mention the above to help explain what this script does.

    This script uses a previously generated CSV file as the basis to scan all CIFS share data for file age, ownership information and explicity ACL rules.  A separate powershell
    script: $scannerScriptPath is launched for each Shares$ listed in the translation CSV file, up to $maxRunSlots at a time.

    The external powershell script, $scannerScriptPath is called to scan each Shares$ listed in $translationCSVPath.  It uses the same translation file passed into this script
    along with the path to scan, and a top level folder where it should save its output.  The output data folder structure is as follows:

    $dataSaveFolder\        # Passed as a parameter to this script.
        <yyyyMMdd-HHmm>\    # Based on when this script is ran.
            <CIFS_Server>\  # Based on what CIFS server is being scanned.

    $dataSaveFolder\<yyyyMMdd-HHmm>            - This is $runFolder and is generated in this script and passed to $scannerScriptPath.
    $runFolder\CIFS_Server                     - Generated in $scannerScriptPath.  Folder for all data for a single CIFS_Server
    $runFolder\CIFS_Server\explicitRules.csv   - Generated in $scannerScriptPath.  Contains all NTFS ACL rules which are not inherited and the path where the rules is applied.
    $runFolder\CIFS_Server\owners.csv          - Generated in $scannerScriptPath.  The users/groups given permission at a "client" share level.
    $runFolder\CIFS_Server\fileAgeData.csv     - Generated in $scannerScriptPath.  Folder and file count and size grouped by age going back 10 years


#>

function WaitForOpenRunSlot
{
    [CmdLetBinding()]
    Param(
        [Parameter(Mandatory=$true,Position=0)]
        [Int32]
        $maxRunSlots
    )


    # Array used to collect all child processes
    $runningChildren = @()
    do {
        $runningChildren = @(Get-CimInstance -Class Win32_Process | Where-Object { $_.ParentProcessID -eq $PID })

        # If $maxRunSlots child processes are running, then take a short break...
        if($runningChildren.Length -ge $maxRunSlots)
        {
            Start-Sleep -Seconds 5
        }
    } while ($runningChildren.Length -ge $maxRunSlots)
}

# Import the data created by ExportNCCIFSSharesToCSV
$allCifsShares = Import-CSV -Delimiter "`t" -Path $translationCSVPath

if($NonRootShares.IsPresent)
{
    # DO NOT Use Shares$ to scan all the files and folders
    $sharesToScan = @($allCifsShares | Where-Object { ($_.ShareName -ne "Shares$") -and (($clustersToInclude.Length -eq 0) -or ($clustersToInclude -contains $_.Cluster)) })
} `
else
{
    # Use Shares$ to scan all the files and folders
    $sharesToScan = @($allCifsShares | Where-Object { ($_.ShareName -eq "Shares$") -and (($clustersToInclude.Length -eq 0) -or ($clustersToInclude -contains $_.Cluster)) })
}

# Create a folder to save all the scan data to
$dt = [DateTime]::Now.ToString("yyyyMMdd-HHmm")
$runFolder = "{0}\{1}" -f @($dataSaveFolder, $dt)
if(-not [System.IO.Directory]::Exists($runFolder))
{
    New-Item -Path $dataSaveFolder -Name $dt -ItemType Directory | Out-Null
}

$a = 0
while($a -lt $sharesToScan.Length)
{
    # Path to scan with $scannerScriptPath, prepend \\?\UNC\ to the path to overcome potential long path issues.
    $pathToScan = "\\?\UNC\{0}\{1}" -f @($sharesToScan[$a].CifsServer, $sharesToScan[$a].ShareName)

    # Wait until there is an open process slot...
    WaitForOpenRunSlot $maxRunSlots

    # Now that there is at least one open "slot", start another scan...
    $processInfo = Start-Process -FilePath powershell.exe -ArgumentList @(
        "-File", $scannerScriptPath,
        "-TranslationCSV", $translationCSVPath,
        "-PathToScan", $pathToScan,
        "-FolderToSaveTo", $runFolder) -PassThru

    # Wait 5 seconds after starting a process...
    Start-Sleep -Seconds 5

    $a++
}

# SIG # Begin signature block
# MIIPMgYJKoZIhvcNAQcCoIIPIzCCDx8CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUxImGO+gDHhPFvc3UNKO1HxHI
# iEOgggyXMIIF3zCCBMegAwIBAgITFQAAAALU9Lz04Hi9mwAAAAAAAjANBgkqhkiG
# 9w0BAQ0FADBGMRMwEQYKCZImiZPyLGQBGRYDY29tMRgwFgYKCZImiZPyLGQBGRYI
# cG93ZXJlbmcxFTATBgNVBAMTDFBFSSBSb290IENBMjAeFw0xNTA4MTIyMDQ2MDVa
# Fw0zNTA4MTIyMDA4MDVaME0xEzARBgoJkiaJk/IsZAEZFgNjb20xGDAWBgoJkiaJ
# k/IsZAEZFghwb3dlcmVuZzEcMBoGA1UEAxMTUEVJIFN1Ym9yZGluYXRlIENBMjCC
# ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKVLzra7Ww5Nmy+NM14MdRZW
# wEhw09fhAIC6jDl90IGt1D0zvB9xrM1XTrSfEWgCNnveOnNSvXBSHjfWYd7KAs8N
# EDLyIjWluCB66bdi/xY2fascuYJvy2ZmA6Voh005/nRS7lPGq6yfZEjc6LXfiaHS
# Wo+kbrFw/ICoq79kEIympaHeO7TYFOcHoP7T/nfWvD0OrJZLrou9m53qQzZXduBV
# pYwfI91CsGR1DpXKwcgC4yPqLdaP9GmWjYYddT6jQTGD/aCIfYo/29z2vXVafaHx
# 90i8OIF7frlhOL39P3GhxIlDk7espdSKxHWF6772N0XXc7NVaq+Jdw7vtpG02yMC
# AwEAAaOCAr0wggK5MBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBQFk+663K25
# Xljs+Tik5+qrsUUojTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8E
# BAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBSwdElPGrGwpa46Uu+0
# SWDcXSTY9TCCAQ8GA1UdHwSCAQYwggECMIH/oIH8oIH5hoG6bGRhcDovLy9DTj1Q
# RUklMjBSb290JTIwQ0EyLENOPUJPSS1SQ0EwMixDTj1DRFAsQ049UHVibGljJTIw
# S2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1w
# b3dlcmVuZyxEQz1jb20/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29i
# amVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50hjpodHRwOi8vY2VydHMyLnBv
# d2VyZW5nLmNvbS9DZXJ0RW5yb2xsL1BFSSUyMFJvb3QlMjBDQTIuY3JsMIIBFwYI
# KwYBBQUHAQEEggEJMIIBBTCBsAYIKwYBBQUHMAKGgaNsZGFwOi8vL0NOPVBFSSUy
# MFJvb3QlMjBDQTIsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENO
# PVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9cG93ZXJlbmcsREM9Y29tP2NB
# Q2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9y
# aXR5MFAGCCsGAQUFBzAChkRodHRwOi8vY2VydHMyLnBvd2VyZW5nLmNvbS9DZXJ0
# RW5yb2xsL0JPSS1SQ0EwMl9QRUklMjBSb290JTIwQ0EyLmNydDANBgkqhkiG9w0B
# AQ0FAAOCAQEAcpv1ZhjtPnt9puHEI7ex1y8Y5l9KFw9/H0d05h104MDMGuD07HDG
# lQfgvSrmghZP86z2WsssNFbUisjr+aQlCtK8kTdfO/lf3agg/GJBPnzqxiJxIlb9
# Y1v0JT4gJf9sZMsXNiiYwatYGecK8DR2UbWDFUMjcIF7MaECWNedh/aWMb4cah2i
# sNP7FbCftZmP4LJ5VynBGTHb3P6DxYG2YzRxpSFeIlDP1aAABoFuKDGIK72izBG2
# QyeB1W2e7/sjFRiSLbyw2GuSuzHm0o4w3PkHQ0H1yiv50jiX02Sl30J/uP4bNAQF
# kC2U3Ov3RefYTwqj4uLKMmkNEqmpxLoySDCCBrAwggWYoAMCAQICE2YAABLaelh+
# 7dzdJlYAAAAAEtowDQYJKoZIhvcNAQENBQAwTTETMBEGCgmSJomT8ixkARkWA2Nv
# bTEYMBYGCgmSJomT8ixkARkWCHBvd2VyZW5nMRwwGgYDVQQDExNQRUkgU3Vib3Jk
# aW5hdGUgQ0EyMB4XDTE2MDMyNDEzNTQzOVoXDTI2MDMyMjEzNTQzOVowgbAxCzAJ
# BgNVBAYTAlVTMQ4wDAYDVQQIEwVJZGFobzEPMA0GA1UEBxMGSGFpbGV5MR0wGwYD
# VQQKExRQT1dFUiBFbmdpbmVlcnMgSW5jLjEWMBQGA1UECxMNT3BlcmF0aW9ucyBJ
# VDFJMEcGA1UEAxNAUE9XRVIgRW5naW5lZXJzIEluZm9ybWF0aW9uIFRlY2hub2xv
# Z3kgSW5mcmFzdHJ1Y3R1cmUgRGVwYXJ0bWVudDCCASIwDQYJKoZIhvcNAQEBBQAD
# ggEPADCCAQoCggEBANo3WBVO5y8uBMYMzLPqdqDkyMcQoJVQR7yPHPKOh/0DeNoZ
# yVM0qXwdV6sZGaotW0+UR2DzyyMvmwxl5zqIIBEvIwjtHFLU/tAEOWamTf9vMwn+
# LxbUVysZ/RCKkv+V56dOnhtYE3vg+NxRBfEZKViQMXHq6FbmpL1LZcDKlYq1t3RO
# gYhbEHYjG5tEJftg11rznA379+K9yWkybUYEEVCavYNQGp/WHlroK9jMg8RtXIaQ
# pI7O/5CLFondPga3eqEU6fjbE3uDsY2ex7Q1+YnjFhvKt7GkosZo+1yWPeykOPra
# TGxqnig+7c8hKHO+ibV9/xfX8q/iWzlLAPQhMZUCAwEAAaOCAyMwggMfMD4GCSsG
# AQQBgjcVBwQxMC8GJysGAQQBgjcVCIHNilODqvxmhZmNOoHT7HuB1rU5gSGC5vp+
# hMywSwIBZAIBCjATBgNVHSUEDDAKBggrBgEFBQcDAzALBgNVHQ8EBAMCB4AwGwYJ
# KwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUY/0hsMlcQdPeIB7Z
# eh3nuq3RuZ8wHwYDVR0jBBgwFoAUBZPuutytuV5Y7Pk4pOfqq7FFKI0wggEjBgNV
# HR8EggEaMIIBFjCCARKgggEOoIIBCoaBwWxkYXA6Ly8vQ049UEVJJTIwU3Vib3Jk
# aW5hdGUlMjBDQTIsQ049Qk9JLVNDQTAyLENOPUNEUCxDTj1QdWJsaWMlMjBLZXkl
# MjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPXBvd2Vy
# ZW5nLERDPWNvbT9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0
# Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnSGRGh0dHA6Ly9CT0ktU0NBMDIucG93
# ZXJlbmcuY29tL0NlcnRFbnJvbGwvUEVJJTIwU3Vib3JkaW5hdGUlMjBDQTIuY3Js
# MIIBNQYIKwYBBQUHAQEEggEnMIIBIzCBtwYIKwYBBQUHMAKGgapsZGFwOi8vL0NO
# PVBFSSUyMFN1Ym9yZGluYXRlJTIwQ0EyLENOPUFJQSxDTj1QdWJsaWMlMjBLZXkl
# MjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPXBvd2Vy
# ZW5nLERDPWNvbT9jQUNlcnRpZmljYXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlm
# aWNhdGlvbkF1dGhvcml0eTBnBggrBgEFBQcwAoZbaHR0cDovL0JPSS1TQ0EwMi5w
# b3dlcmVuZy5jb20vQ2VydEVucm9sbC9CT0ktU0NBMDIucG93ZXJlbmcuY29tX1BF
# SSUyMFN1Ym9yZGluYXRlJTIwQ0EyLmNydDANBgkqhkiG9w0BAQ0FAAOCAQEAcMQQ
# HArQMPorMDdTv0PIeU80NpxlZm6ZjMLHJIWtyKWNRmuG1Oc+Ti762snW05yq5aEY
# kwmmWtm/00ukV4z/DhYrlCuxbmKeQP4kIZoVo4/7K7HrdG0u6QN4SmG9rTJGCuXz
# EXlKZIeHiwgD2EsNa7varVK3jX8CEik1jJh8II0VIbBzvetAMm1QGUCk9/WtllYG
# 76CLyPasgcfFsOlMeRWoHKNw/oV4AvMab0yuQCDJ9uNG3dU+6jGoxDz+ksAKl9OO
# u+zBNs+EOR/TWBD0JfE9hdChCzrbyG6JPIQdOsBoqo822QoIGc8emp4MTeDnCTTh
# ojIQLkYA7bMGDxIxHjGCAgUwggIBAgEBMGQwTTETMBEGCgmSJomT8ixkARkWA2Nv
# bTEYMBYGCgmSJomT8ixkARkWCHBvd2VyZW5nMRwwGgYDVQQDExNQRUkgU3Vib3Jk
# aW5hdGUgQ0EyAhNmAAAS2npYfu3c3SZWAAAAABLaMAkGBSsOAwIaBQCgeDAYBgor
# BgEEAYI3AgEMMQowCKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEE
# MBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEWBBQT
# l9g33ZI3bHhSnkRu5U3nlkd7qjANBgkqhkiG9w0BAQEFAASCAQCaDZovwpCtqhNF
# XfbAC8UmAZzhkY3Wd4MPtghdAawU9CeWLhft7QqadBoWDALGz5KX9iVqYYDNBD3I
# JjfbtbfO63WHfL0c3V+p0vT80L0RlSP7hTXEgqbvgwn2SLZERQShf80/v6GN6njC
# WX3U1TsvE6Dggx78+iQIoL9cSlXOZYIgtEdGU/1d3Mt5cxcDZyevVlu2jXL/8C5v
# tj/xJaqxTsh9oW1h5cZgCVfMykzw5qa2mg/ZGzKcSzOljXS7lDPlo3e1jIadbH51
# Fi0Yf2G1REhHaGstxLl7zXtbDhHO9Y9P03C52UZ6tNATzMZDfui1cMmbvbuZK3Gf
# leLpPlPT
# SIG # End signature block
