USE [StorageInformation]
GO

/****** Object:  Table [dbo].[DatastoreData]    Script Date: 6/7/2021 3:02:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DatastoreData](
	[RunID] [int] NOT NULL,
	[VolumeUUID] [uniqueidentifier] NOT NULL,
	[ID] [nvarchar](100) NOT NULL
) ON [PRIMARY]
GO

/****** Object:  Index [IX_ID]    Script Date: 6/7/2021 3:02:07 PM ******/
CREATE NONCLUSTERED INDEX [IX_ID] ON [dbo].[DatastoreData]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [IX_RunID]    Script Date: 6/7/2021 3:02:13 PM ******/
CREATE NONCLUSTERED INDEX [IX_RunID] ON [dbo].[DatastoreData]
(
	[RunID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [IX_VolumeUUID]    Script Date: 6/7/2021 3:02:20 PM ******/
CREATE NONCLUSTERED INDEX [IX_VolumeUUID] ON [dbo].[DatastoreData]
(
	[VolumeUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

