
CREATE LOGIN [POWERENG\SRVC-AllStorage-RO] FROM WINDOWS;
GO
USE StorageInformation;
GO
CREATE USER [POWERENG\SRVC-AllStorage-RO] FROM LOGIN [POWERENG\SRVC-AllStorage-RO];
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.AggregateData TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Aggregates TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Clusters TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.DataCollectionRuns TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.DatastoreData TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Datastores TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.ShareData TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.SnapmirrorData TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.SnapshotData TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.VirtualMachine_DatastoreData TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.VirtualMachineData TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.VolumeData TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Volumes TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.VServers TO [POWERENG\SRVC-AllStorage-RO]
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.VirtualMachines TO [POWERENG\SRVC-AllStorage-RO]
