<#
.SYNOPSIS
Checks NetApp VMware volume SMVI snapshots and makes sure the oldest backup isn't more than 8 days old and the newest backup isn't older than 2 days old.

.DESCRIPTION
This script connects to each CDOT cluster and 7-Mode node and gathers configuration information. This information can
    be used to rebuild in the event of a DR scenario.

.EXAMPLE
.\netappConfigBackup.ps1

.PARAMETER $logFileBasePath
This parameter defines the base path for the log output file of the script. (Where logs will be written)

.PARAMETER $logFileBaseName
The parameter defines the root of the scripts log output file name.

.PARAMETER $sendTo
This parameter defines the email destination for the standard script email output.

.PARAMETER $from
This parameter defines the from address for emails generated by the script.

.PARAMETER $subject
This parameter defines the subject for the standare output email from the script.

.PARAMETER $smtpServer
This parameter defines the SMTP server to be used when the script sends an email.

.PARAMETER $subjectFail
This parameter defines the subject of the failure related email output.

.PARAMETER $cdotClusterListFile
This parameter defines the text file that contains all of the CDOT clusters to pull data from.

.PARAMETER $logFileRetentionDays
This parameter defines how long this script's log files are retained.

.PARAMETER $dataFileRetentionDays
This parameter defines how long the output data files from this script are kept.

.PARAMETER $backupAgeThreshold
This parameter defines the age upon which the script will alert for orphaned backup snapshots.

.PARAMETER $newestBackupDaysThreshold
This parameter defines the age upon which the script will alert that the most recent backup is too old and the previous backup job must have failed or have not run.

.NOTES
Author: duane.reed@powereng.com
Last revised: 25-Jan-17

Any other notes about the script (revision history, etc.)
Initial version 0.1 (25-Jan-17)

.LINK
An external link if needed. The syntax of comment-based help is available here:
http://technet.microsoft.com/en-us/library/hh847834.aspx

#>

#Configure script command line parameters
[cmdletbinding()]
Param
(
    [String]$logFileBasePath = "E:\Scripts\Logs\SMVI Backup Check\",
    [String]$logFileBaseName = "netappSMVIBackupCheck",
    #$sendTo can accept multiple email addresses
    [String]$sendTo = "itstorage@powereng.com",
    #[String]$sendTo = "ken.briney@powereng.com",
    [String]$from = "cdc-ntapmgmt01@powereng.com",
    [string]$subject = "VM Backup Orphaned Snapshots",
    [string]$problemSubject = "Recent VM Backup Failure",
    [string]$smtpServer = "smtp.powereng.com",
    [string]$subjectFail = "FAILED :: NetApp SMVI Backup Check",
    [String]$cdotClusterListFile = "E:\Scripts\Config\cdotList.txt",
    [int]$logFileRetentionDays = 30,
    [int]$dataFileRetentionDays = 7,
    [int]$backupAgeThreshold = 8,
    [int]$newestBackupDaysThreshold = 1
)

# Logging function
Function Out-LogFile
{
    <#
    .SYNOPSIS
    Writes data to a log file

    .DESCRIPTION
    Writes data to a log file. The format of the log file attempts to mimic the logging
    used by Configuration Manager, so that the log files will render nicely using cmtrace.

    .PARAMETER logText
    This is the string that will be written to the log file

    .PARAMETER overwrite
    By default, log file entries are appended to the specified log file. If this switch is specified,
    the log file will be overwritten.

    .PARAMETER type
    Determines the type of message that will be written to a log. The default value is 1:
    1 - Information
    2 - Warning
    3 - Error

    .PARAMETER logFile
    The name of the log file where messages will be written.
    #>

    Param
    (
        [String]$logText,
        [Switch]$overwrite,
        [string]$type = 1,
        [String]$logFile = $logFile
    )

    # Do nothing if no log file is defined
    if (!$logFile)
    {
        return
    }
    else
    {
        #Create the time stamp for the log entry
        $time = Get-Date -Format HH:mm:ss.fff
        $offset = ([int](Get-Date -Format %z) * -60).ToString().PadLeft(3, "0").PadLeft(4, "+")
        $day = Get-Date -Format MM-dd-yyyy
        $component = $MyInvocation.ScriptName | Split-Path -Leaf
        $string = "<![LOG[$logText]LOG]!>" +
        "<time=`"$time$offset`" " +
        "date=`"$day`" " +
        "component=`"$component`" " +
        "context=`"$env:USERNAME`" " +
        "type=`"$type`" " +
        "thread=`"$PID`" " +
        "file=`"$component`">"
        #Write the data to the log file
        Write-Verbose $logText
        $string | Out-File  -FilePath $logFile -Force -Encoding utf8 -Append:$(!$overwrite)
    }#End else
}#End Out-Log Function

$date = Get-Date -Format MM-dd-yyyy_HHmmss

if ($date)
{
    $logfile = $logFileBasePath + $logFileBaseName + $date + ".log"
}
else
{
    $logfile = $logFileBasePath + $logFileBasePath + ".log"
}

if (!(Test-Path -Path $logFileBasePath))
{
    New-Item -Path $logFileBasePath -ItemType "Directory" | Out-Null
}

# Check if the $PSScriptRoot variable is defined and define it
if ($null -eq $PSScriptRoot)
{
    #####Out-LogFile "PSScriptRoot was Null"
    $PSScriptRoot = $MyInvocation.MyCommand.Path | Split-Path
}

#=========================END SKELETON=========================#

#=================================================================================================================
#
# For CDOT connections, since they use https, you have to catpure logins via the NetApp Powershell toolkit
#  so that they can be accessed magically when you run a scheduled task non-interactively.
#
# To capture credentials (encrypted of course) to be available at scheduled task run time, perform the following.
#
#  First: Capture login and password as follows:
#   $credentials = Get-Credential -Credential POWERENG\<ACCOUNT NAME>
#
#  Second: Add the capture credentials to the NetApp PowerShell toolkit cache.
#   Add-NcCredential -Name "<CLUSTER FQDN>" -Credential $credentials
#   Repeat this r
#
#  Third: Verify credentials
#   Get-NcCredential
#
#==================================================================================================================

Function Remove-OldFiles
{
    [cmdletbinding()]
    Param (
        [String]$path,
        [Int]$daysToKeep = 7,
        [String]$includeFilter = "*.csv",
        [Switch]$recurse,
        [Switch]$delete
    )

    #Correct path input.

    if ($recurse.IsPresent)
    {
        if ($path.EndsWith("/"))
        {
            $path = $path.Replace("/", "\")
        }
    }
    else
    {
        if ($path.EndsWith("\"))
        {
            $path += "*"
        }

        if ($path.EndsWith("/"))
        {
            $path = $path.Replace("/", "\")
            $path += "*"
        }

        if (!$path.EndsWith("\*"))
        {
            $path += "\*"
        }
    }

    $maxAge = (Get-Date).AddDays(-$daysToKeep)

    if (Test-Path $path.Replace("*", ""))
    {
        if ($maxAge)
        {
            if ($recurse.IsPresent)
            {
                #Write-Host "`nRecursion enabled.`n"
                Out-LogFile -logText "[Remove-OldFiles] Recursion enabled."
                Try
                {
                    $oldFiles = Get-ChildItem -File -Recurse -Path $path -Include $includeFilter -ErrorAction SilentlyContinue -ErrorVariable getChildErrors | Where-Object { $_.LastWriteTime -lt $maxAge }
                }
                catch
                {
                    Out-LogFile "`n`n[Remove-OldFiles] Errors encountered while collecting child items.`n`nError message: $($_.Exception.Message)`n`n"
                }
            }
            else
            {
                Out-LogFile "`n[Remove-OldFiles] Recursion disabled."
                Try
                {
                    $oldFiles = Get-ChildItem -File -Path $path -Include $includeFilter -ErrorAction SilentlyContinue -ErrorVariable getChildErrors | Where-Object { $_.LastWriteTime -lt $maxAge } -ErrorAction Stop
                }
                catch
                {
                    Out-LogFile "[Remove-OldFiles] $($_.Exception.Message)"
                }
            }

            if ($oldFiles)
            {
                if (!$delete.IsPresent)
                {
                    Out-LogFile "[Remove-OldFiles] Delete switch not present. Logging files that would be deleted with `$delete switch enabled.`n"
                }

                foreach ($file in $oldFiles)
                {
                    if ($delete.IsPresent)
                    {
                        try
                        {
                            Remove-Item $file -ErrorAction Stop
                            Out-LogFile "[Remove-OldFiles] Successfully removed $file"
                        }
                        catch
                        {
                            Out-LogFile "[Remove-OldFiles] Failed to remove $file"
                        }
                    }
                    else
                    {
                        Out-LogFile "[Remove-OldFiles] Would delete $file if -delete was specified when calling the function."
                    }
                }
            }
            else
            {
                Out-LogFile "`n[Remove-OldFiles] No files found. Exiting."
            }
        }
        else
        {
            Out-LogFile "[Remove-OldFiles] Maximum age was not calculated. Cannot continue."
        }
    }
    else
    {
        Out-LogFile "[Remove-OldFiles] Path, $path, not found."
    }

    if ($getChildErrors)
    {
        Write-Host "`n"
        foreach ($object in $getChildErrors)
        {
            Out-LogFile "[Remove-OldFiles] Failure: $($object.Exception.Message)`n"
        }
    }
}


Function Connect-Cluster
{
    Param
    (
        $clusters
    )

    foreach ($cluster in $clusters)
    {
        Out-LogFile "Connecting to CDOT cluster $cluster."
        $connection = Connect-NcController -Name $cluster

        if ($connection)
        {
            [void]$cdotConnectionArrayList.Add($connection)
        }
        else
        {
            Out-LogFile "FAILURE: Could not connect to $cluster."
            Write-Host "FAILURE: Could not connect to $cluster."
            $Script:failMessages += "FAILURE: Could not connect to $cluster.`n"
        }

        $connection = $null
    }
}

if (!(Get-Module -Name DataONTAP))
{
    Import-Module DataONTAP
}


if (Test-Path -Path $cdotClusterListFile)
{
    #Clean up old script log files
    #Remove-OldFiles -path $logFileBasePath -daysToKeep $logFileRetentionDays -includeFilter "*.log" -recurse -delete

    #Clean up old data CSV files
    #Remove-OldFiles -path $destinationPath -daysToKeep $dataFileRetentionDays -includeFilter "*.csv" -recurse -delete

    #Confgure HTML settings
    $html = "<style>"
    $html = $html + "BODY{background-color:White;}"
    $html = $html + "TABLE{border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}"
    $html = $html + "TH{border-width: 1px;padding: 5px;border-style: solid;border-color: black;background-color: green}"
    $html = $html + "TD{border-width: 1px;padding: 5px;text-align: center;border-style: solid;border-color: black;background-color: Silver}"
    $html = $html + "</style>"

    #Create the volume mail object.
    $reportMessage = New-Object System.Net.Mail.MailMessage $from, $sendTo
    $problemMessage = New-Object System.Net.Mail.MailMessage $from, $sendTo

    #Create the SMTP client object.
    $smtp = New-Object Net.Mail.SmtpClient($smtpServer)

    $problemSMTP = New-Object Net.Mail.SmtpClient($smtpServer)

    $currentDate = Get-Date

    $newestBackupDays = $null
    $newestBackup = $null

    $cdotConnectionArrayList = New-Object System.Collections.ArrayList
    $oldSMVISnapshots = @()
    $newestSMVISnapshot = @()

    $cdotClusterList = Get-Content -Path $cdotClusterListFile

    # We don't care about volumes which match the follow...
    $volumesToIgnoreRegex = "^(JP_)|(ROOT_)|(vol0)|(SMD_)|(SL_)"

    foreach ($cluster in $cdotClusterList)
    {
        Connect-Cluster $cluster
    }
$a = 0
    #foreach ($cdotConnection in $cdotConnectionArrayList)
    while($a -lt $cdotConnectionArrayList.Length)
    {
        $cdotConnection = $cdotConnectionArrayList[$a]
        $vmwareVolumes = Get-NcVol -Controller $cdotConnection | Where-Object { (($_.Name -like "*vmware*") -and (($_.Name -notlike "*SMD*") -and ($_.Name -notlike "*LSM_vol*") -and ($_.Name -notlike "*JP_vol*") -and ($_.Name -notlike "*ROOT_vol*"))) }

        foreach ($volume in $vmwareVolumes)
        {
            $snapShots = Get-NcSnapshot -Controller $cdotConnection -Volume $volume | Where-Object { $_.Name -like "*SnapCenterBkp*" } | Select-Object Name, Created, Vserver, Volume
            Write-Host ("Processing volume: {0} / {1} snapshots" -f @($volume.Name, $snapShots.Length))

            foreach ($snapShot in $snapShots)
            {
                $snapShotDate = $snapShot.Created
                $age = $currentDate - $snapShotDate

                if ($null -eq $newestBackupDays)
                {
                    $newestBackupDays = $age.TotalDays
                    $newestBackup = $snapShot
                    Write-Host ("`tnewer snapshot: {0}" -f @($newestBackupDays))
                }
                elseif ($age.TotalDays -lt $newestBackupDays)
                {
                    $newestBackupDays = $age.TotalDays
                    $newestBackup = $snapShot
                    Write-Host ("`tnewer snapshot: {0}" -f @($newestBackupDays))
                }

                #Write-Host "This snapshot is $($snapShot.Name) and it was created on $snapShotDate for SVM $($volume.Vserver) on volume $volume."
                if ($age.TotalDays -gt $backupAgeThreshold)
                {
                    $snapItem = New-Object System.object

                    $formattedDays = "{0:N2}" -f $age.TotalDays

                    $snapItem | Add-Member -MemberType NoteProperty -Name "Vserver" -Value $snapshot.Vserver
                    $snapItem | Add-Member -MemberType NoteProperty -Name "Volume" -Value $snapshot.Volume
                    $snapItem | Add-Member -MemberType NoteProperty -Name "Age-Days" -Value $formattedDays
                    $snapItem | Add-Member -MemberType NoteProperty -Name "Snapshot-Name" -Value $snapshot.Name
                    $snapItem | Add-Member -MemberType NoteProperty -Name "Snapshot-Created" -Value $snapshot.Created

                    Write-Host "Orphaned snapshot found :: Age in days is $formattedDays for snapshot $($snapShot.Name), with a creation date of $($snapshot.Created), for SVM $($volume.Vserver) on volume $volume";

                    $oldSMVISnapshots += $snapItem
                }

                $snapShotDate = $null
                $age = $null
                $formattedDays = $null
            }

            # Write-host "`$newBackupDays is $newBackupDays"

            if ($newestBackupDays -gt $newestBackupDaysThreshold)
            {
                $staleAge = $currentDate - $newestBackup.Created

                $formattedStaleDays = "{0:N2}" -f $staleAge.TotalDays

                $newestSnapItem = New-Object System.Object

                $newestSnapItem | Add-Member -MemberType NoteProperty -Name "Vserver" -Value $newestBackup.Vserver
                $newestSnapItem | Add-Member -MemberType NoteProperty -Name "Volume" -Value $newestBackup.Volume
                $newestSnapItem | Add-Member -MemberType NoteProperty -Name "Age-Days" -Value $formattedStaleDays
                $newestSnapItem | Add-Member -MemberType NoteProperty -Name "Snapshot-Name" -Value $newestBackup.Name
                $newestSnapItem | Add-Member -MemberType NoteProperty -Name "Created" -Value $newestBackup.Created

                $newestSMVISnapshot += $newestSnapItem

                Write-Host "Most recent backup is too old. Assuming failure on volume $($volume.Name). Snapshot is $($newestBackup.Name) and was created on $($newestBackup.Creataed) for vserver $($newestBackup.Vserver)"
            }

            $snapShots = $null
            $newestBackupDays = $null
            $newestBackup = $null
            $formattedStaleDays = $null
        }
        $a++
    }

    if ($oldSMVISnapshots)
    {
        Out-LogFile "Sending orphaned backup report to $sendTo using server $smtpServer."

        $reportMessage.Subject = $subject
        $reportMessage.Body = $oldSMVISnapshots | ConvertTo-Html -Head $html
        $reportMessage.IsBodyHTML = $true

        #Send it!
        $smtp.Send($reportMessage)
        $smtp.Dispose()
    }

    if ($newestSMVISnapshot)
    {
        Out-LogFile "Sending potential backup failures report to $sendTo using server $smtpServer."

        $problemMessage.Subject = $problemSubject
        $problemMessage.Body = $newestSMVISnapshot | ConvertTo-Html -Head $html
        $problemMessage.IsBodyHTML = $true

        #Send it!
        $problemSMTP.Send($problemMessage)
        $problemSMTP.Dispose()
    }
}
else
{
    Out-Logfile "FAILURE: Could not find the cdot file, $cdotClusterListFile."
    Write-Host "FAILURE: Could not find the cdot file, $cdotClusterListFile."
    $failMessages += "FAILURE: Could not find the cdot file, $cdotClusterListFile.`n"
}
