[CmdLetBinding()]
Param(
    # CSV File generated by ExportNCCIFSSharesToCSV.
    [Parameter(Mandatory=$true,Position=0)]
    [String]
    $translationCSVPath,

    # Top level folder where individual scan data is saved to.
    [Parameter(Mandatory=$true,Position=1)]
    [String]
    $dataSaveFolder,

    # Path to an external script used to scan each Shares$ share listed in $translationCSVPath
    [Parameter(Mandatory=$true,Position=2)]
    [String]
    $scannerScriptPath,     # "C:\Users\kbriney-adm\PSScripts\Repos\PEI-IT-OPS\Dataclassification\shell.ps1"

    # Maximum number of $scannerScriptPath script to allow at a time
    [Parameter(Mandatory=$false,Position=3)]
    [Int32]
    $maxRunSlots =  15
)


<#
    POWER Engineers CIFS shares are hosted on NetApp ONTAP clusters.  They all use the following pattern.

    CIFS_Server
        Shares$      Hidden share at the top of all shares hosted from a CIFS Server
            Share01
            Share02
            Share03

    In the above example user data would be accessed using \\CIFS_Server\Share01, \\CIFS_Server\Share03, or \\CIFS_Server\Share03.  However, \\CIFS_Server\Shares$ would also
    allow access to Share01, Share02, and Share03 as follows: \\CIFS_Server\Shares$\Share01, \\CIFS_Server\Shares$\Share02, and \\CIFS_Server\Shares$\Share03.  Knowing this,
    it is possible to scan all shares using a single share...Shares$.

    Most of the heavy lifting is in another script: $scannerScriptPath.  I mention the above to help explain what this script does.

    This script uses a previously generated CSV file as the basis to scan all CIFS share data for file age, ownership information and explicity ACL rules.  A separate powershell
    script: $scannerScriptPath is launched for each Shares$ listed in the translation CSV file, up to $maxRunSlots at a time.

    The external powershell script, $scannerScriptPath is called to scan each Shares$ listed in $translationCSVPath.  It uses the same translation file passed into this script
    along with the path to scan, and a top level folder where it should save its output.  The output data folder structure is as follows:

    $dataSaveFolder\        # Passed as a parameter to this script.
        <yyyyMMdd-HHmm>\    # Based on when this script is ran.
            <CIFS_Server>\  # Based on what CIFS server is being scanned.

    $dataSaveFolder\<yyyyMMdd-HHmm>                          - This is $runFolder and is generated in this script and passed to $scannerScriptPath.
    $runFolder\<CIFS_Server>\<ShareName>                     - Generated in $scannerScriptPath.  Folder for all data for a single CIFS_Server
    $runFolder\<CIFS_Server>\<ShareName>\explicitRules.csv   - Generated in $scannerScriptPath.  Contains all NTFS ACL rules which are not inherited and the path where the rules is applied.
    $runFolder\<CIFS_Server>\<ShareName>\owners.csv          - Generated in $scannerScriptPath.  The users/groups given permission at a "client" share level.
    $runFolder\<CIFS_Server>\<ShareName>\fileAgeData.csv     - Generated in $scannerScriptPath.  Folder and file count and size grouped by age going back 10 years


#>

function WaitForOpenRunSlot
{
    [CmdLetBinding()]
    Param(
        [Parameter(Mandatory=$true,Position=0)]
        [Int32]
        $maxRunSlots
    )


    # Array used to collect all child processes
    $runningChildren = @()
    do {
        $runningChildren = @(Get-CimInstance -Class Win32_Process | Where-Object { $_.ParentProcessID -eq $PID })

        # If $maxRunSlots child processes are running, then take a short break...
        if($runningChildren.Length -ge $maxRunSlots)
        {
            Start-Sleep -Seconds 5
        }
    } while ($runningChildren.Length -ge $maxRunSlots)
}

# Import the data created by ExportNCCIFSSharesToCSV
$allCifsShares = Import-CSV -Delimiter "`t" -Path $translationCSVPath

# Use Shares$ to scan all the files and folders
$clientShares = @($allCifsShares | Where-Object { $_.ShareName -ne "Shares$" })

# Create a folder to save all the scan data to
$dt = [DateTime]::Now.ToString("yyyyMMdd-HHmm")
$runFolder = "{0}\{1}" -f @($dataSaveFolder, $dt)
if(-not [System.IO.Directory]::Exists($runFolder))
{
    New-Item -Path $dataSaveFolder -Name $dt -ItemType Directory | Out-Null
}

$a = 0
while($a -lt $clientShares.Length)
{
    # Path to scan with $scannerScriptPath, prepend \\?\UNC\ to the path to overcome potential long path issues.
    $pathToScan = "\\?\UNC\{0}\{1}" -f @($clientShares[$a].CifsServer, $clientShares[$a].ShareName)

    # Wait until there is an open process slot...
    WaitForOpenRunSlot $maxRunSlots

    # Now that there is at least one open "slot", start another scan...
    $processInfo = Start-Process -FilePath powershell.exe -ArgumentList @(
        "-NoExit",
        "-File", $scannerScriptPath,
        "-TranslationCSV", $translationCSVPath,
        "-PathToScan", $pathToScan,
        "-FolderToSaveTo", $runFolder) -PassThru

    # Wait 5 seconds after starting a process...
    Start-Sleep -Seconds 5

    $a++
}
